### ISSUE TITLE
Executar job do Jenkins

### ISSUE THREAD

**Issue by pietrocaselani** [involvestecnologia/AgileBOT#7]
Em um futuro, quando o jenkins não estiver preso na nossa rede, seria bacana mandar o bot executar os jobs. Pensei em algo como `bot jenkins <nome do job>`

**Comment by fernandovsv** [comment]
Esse aqui eu acho que vamos ter que fazer do 0 mesmo... fiz testes com alguns scripts que prometiam isso e nenhum funcionou como o esperado :(
